### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by umbrella-alexander-ageychenko** [terrakok/Cicerone#85] opened 2018-10-12 14:02 UTC
```
/**
     * Clear current stack and open several screens inside single transaction.
     * @param screens
     */
    public void newRootChain(Screen... screens) {
        Command[] commands = new Command[screens.length + 1];
        commands[0] = new BackTo(null);
        for (int i = 0; i < commands.length; i++) {
            commands[i + 1] = new Forward(screens[i]);
        }
        executeCommands(commands);
    }
```

This function always results in `ArrayIndexOutOfBoundsException` because of iteration comparison with `commands.lenght`, and it should compare to `screens.lenght`

**Comment by the-rs** [comment] 2018-10-13 17:30
Duplicate of #82

**Comment by terrakok** [comment] 2018-10-13 18:38
Do you use latest Cicerone version?

**Comment by terrakok** [comment] 2018-11-02 19:10
Fixed

**Closed** 2018-11-02 19:10 UTC
